#!/usr/bin/env python3
"""Copy Malla data from SQLite into PostgreSQL.

This is a preparation/migration helper. It does not switch the running
application to PostgreSQL; it only creates compatible tables and copies data.
"""

from __future__ import annotations

import argparse
import sqlite3
from collections.abc import Iterable
from typing import Any

import psycopg
from psycopg import sql


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Migrate Malla tables from SQLite to PostgreSQL."
    )
    parser.add_argument("--sqlite-path", required=True, help="Path to SQLite database")
    parser.add_argument(
        "--postgres-dsn",
        required=True,
        help="PostgreSQL DSN, e.g. postgresql://malla:secret@127.0.0.1:5432/malla",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=1000,
        help="Rows per insert batch (default: 1000)",
    )
    parser.add_argument(
        "--truncate",
        action="store_true",
        help="Truncate target tables before inserting data",
    )
    return parser.parse_args()


def map_sqlite_type_to_postgres(sqlite_type: str) -> str:
    normalized = (sqlite_type or "").upper()
    if "INT" in normalized:
        return "BIGINT"
    if any(token in normalized for token in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BLOB" in normalized:
        return "BYTEA"
    if "BOOL" in normalized:
        return "BOOLEAN"
    return "TEXT"


def iter_user_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    return [row[0] for row in rows]


def table_columns(conn: sqlite3.Connection, table_name: str) -> list[sqlite3.Row]:
    return conn.execute(f"PRAGMA table_info({table_name})").fetchall()


def create_table(pg_conn: psycopg.Connection, table_name: str, columns: list[sqlite3.Row]) -> None:
    column_defs: list[sql.Composed] = []

    for column in columns:
        is_integer_pk = (
            column["pk"]
            and column["name"] == "id"
            and "INT" in (column["type"] or "").upper()
        )
        parts: list[sql.SQL | sql.Identifier] = [sql.Identifier(column["name"])]
        if is_integer_pk:
            parts.append(sql.SQL("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"))
        else:
            parts.append(sql.SQL(map_sqlite_type_to_postgres(column["type"])))
            if column["pk"]:
                parts.append(sql.SQL("PRIMARY KEY"))
        if column["notnull"]:
            parts.append(sql.SQL("NOT NULL"))
        column_defs.append(sql.SQL(" ").join(parts))

    query = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(
        sql.Identifier(table_name),
        sql.SQL(", ").join(column_defs),
    )
    with pg_conn.cursor() as cur:
        cur.execute(query)


def truncate_table(pg_conn: psycopg.Connection, table_name: str) -> None:
    with pg_conn.cursor() as cur:
        cur.execute(
            sql.SQL("TRUNCATE TABLE {} RESTART IDENTITY").format(
                sql.Identifier(table_name)
            )
        )


def batched(rows: Iterable[tuple[Any, ...]], batch_size: int) -> Iterable[list[tuple[Any, ...]]]:
    batch: list[tuple[Any, ...]] = []
    for row in rows:
        batch.append(row)
        if len(batch) >= batch_size:
            yield batch
            batch = []
    if batch:
        yield batch


def convert_value(value: Any, sqlite_type: str) -> Any:
    normalized = (sqlite_type or "").upper()
    if value is None:
        return None
    if "BOOL" in normalized:
        return bool(value)
    return value


def copy_rows(
    sqlite_conn: sqlite3.Connection,
    pg_conn: psycopg.Connection,
    table_name: str,
    columns: list[sqlite3.Row],
    batch_size: int,
) -> int:
    column_names = [column["name"] for column in columns]
    select_query = f"SELECT {', '.join(column_names)} FROM {table_name}"
    rows = sqlite_conn.execute(select_query)

    insert_query = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
        sql.Identifier(table_name),
        sql.SQL(", ").join(sql.Identifier(name) for name in column_names),
        sql.SQL(", ").join(sql.Placeholder() for _ in column_names),
    )
    sqlite_types = [column["type"] for column in columns]

    inserted = 0
    with pg_conn.cursor() as cur:
        for batch in batched(
            (
                tuple(
                    convert_value(row[idx], sqlite_types[idx])
                    for idx in range(len(column_names))
                )
                for row in rows
            ),
            batch_size,
        ):
            cur.executemany(insert_query, batch)
            inserted += len(batch)
    return inserted


def main() -> None:
    args = parse_args()

    sqlite_conn = sqlite3.connect(args.sqlite_path)
    sqlite_conn.row_factory = sqlite3.Row

    with psycopg.connect(args.postgres_dsn) as pg_conn:
        pg_conn.autocommit = False
        tables = iter_user_tables(sqlite_conn)

        for table_name in tables:
            columns = table_columns(sqlite_conn, table_name)
            if not columns:
                continue

            print(f"Preparing table {table_name}...")
            create_table(pg_conn, table_name, columns)
            if args.truncate:
                truncate_table(pg_conn, table_name)

            inserted = copy_rows(
                sqlite_conn=sqlite_conn,
                pg_conn=pg_conn,
                table_name=table_name,
                columns=columns,
                batch_size=args.batch_size,
            )
            pg_conn.commit()
            print(f"  inserted {inserted} rows")

    sqlite_conn.close()
    print("Migration completed.")


if __name__ == "__main__":
    main()
